version: '3.8'
services:
  frontend:
    build: ./site
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - api
    volumes:
      - ./site:/app

  api:
    build: ./api
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./api:/app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: aipac
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

  worker:
    build: ./automation
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./automation:/app

volumes:
  db-data:
